name: 'Update Version'

description: 'Update the package version'

inputs:
  release-as:
    description: 'Type of release (patch, minor, major)'
    required: false
    default: 'patch'
  token:
    description: 'Token having specific permissions'
    required: true
  url:
    description: 'Repo url'
    required: true

outputs:
  released-version:
    description: 'Release version'

runs:
  using: 'node16'
  main: 'action/index.js'