name: 'Update Version'

description: 'Update the package version.'

inputs:
  release-as:
    description: 'Type of release (patch, minor).'
    required: false
    default: 'patch'
  token:
    description: 'Token used by release-please to update version.'
    required: false
  url:
    description: 'Repository url.'
    required: false
  git-user-name:
    description: 'The user name to be configured for Git.'
    required: false
  git-user-email:
    description: 'The email address to be configured for Git.'
  empty-commit:
    description: 'Specify if it is just an empty commit. Set to "true" or "false".'
    default: false
    required: true
  operation-mode:
    description: "Operation mode of the action (update-version or push-tags)"
    required: true
    default: "update-version"
outputs:
  tagging-status:
    description: "Tells the status of git tag command execution."

runs:
  using: 'node18'
  main: 'action/index.js'