name: 'Update Version'

description: 'Update the package version'

inputs:
  file-path:
    description: 'Path to the file to update'
    required: true
  release-type:
    description: 'Type of release (patch, minor, major)'
    required: false
    default: 'patch'
  token:
    description: 'token having write permissions'
    required: true
  url:
    description: 'repo url'
    required: true

runs:
  using: 'node12'
  main: 'index.js'